# name: Publish DockerHub image

# on:
#   push:
#     branches:
#       - "main"
#     tags:
#       - "v*"
#   push_request:
#     branches:
#       - "main"

# jobs:
#   build-container:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-actions@v3
#         with:
#           images: itsmetommy/hello-github-actions

#       - name: Build and Push
#         uses: docker/build-push-actions@v2
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.met.outputs.tags }}
#           labels: ${{ step.meta.outputs.labels }}
